### PR TITLE
added custom transposition rule for linear system of implicit differentiation

### PR DESCRIPTION
**Pull request by ersisimou**

### CODE REVIEW

**Comment by ersisimou** [comment]
Hi @froystig,

 In order to define  a ``custom_vjp`` rule with a linear system, I used a custom transposition as mentioned at [this comment](https://github.com/ott-jax/ott/pull/161#discussion_r1013934139). 

When I use the custom transposition to solve the linear system my implementation works. However, when I use the linear system as a custom vjp I get the error ``NotImplementedError: Batching rule for 'linear_call' not implemented``.  To my understanding this is due to the ``_custom_vjp_call_jaxpr_vmap`` which would then require that ``api.linear_call`` could also be vmaped. It seems however that this is not the case. Is there perhaps a workaround for this so that one can vmap functions that use custom transposition?

Many thanks in advance!

**Comment by michalk8** [comment]
I think this can be closed now for inactivity - there doesn't seem to be an obvious solution at the moment.

**Comment by froystig** [comment]
Closing the issue brought a notification to the top of my queue!

@ersisimou – Custom transposition in JAX isn't complete yet (relatedly, it isn't yet documented nor part of a supported API). In particular, it doesn't yet support batching (`vmap`), which I suspect is why you're seeing that `NotImplementedError`. You can follow https://github.com/google/jax/issues/9129 for gradual progress updates, but development will take a while longer.

For now, a couple of ideas:
* Could you express what you need using [`jax.lax.custom_linear_solve`](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.custom_linear_solve.html)?
* You could consider [writing your own JAX primitive](https://jax.readthedocs.io/en/latest/notebooks/How_JAX_primitives_work.html). This will give you full control of transposition and more, but it requires substantially more work too: in addition to your transposition rule, you'll also need to write a batching rule, a JVP rule, a JIT-lowering rule, and so on. This is not an officially [supported API](https://jax.readthedocs.io/en/latest/api_compatibility.html), so it may take more care to maintain your custom primitive across JAX versions.

**Comment by ersisimou** [comment]
Hi @froystig,

Many thanks for the response! Let me look into these suggestions and I will get back to you.

**Comment by patrick-kidger** [comment]
Would Lineax (https://github.com/google/lineax) be helpful here? It's our newly-released library for linear solvers. It supports transposition. (And custom solvers, if you need that.)

**Comment by marcocuturi** [comment]
Thanks Patrick, yes, this looks very relevant indeed. @michalk8 we should take a look at lineax!

**Comment by marcocuturi** [comment]
@patrick-kidger , from what I see in https://docs.kidger.site/lineax/examples/no_materialisation/, you currently offer to use normalized CG to handle non symmetric problems. This is currently what is done in OTT-JAX (e.g. [here](https://github.com/ott-jax/ott/blob/31df7014ac0cadb879e17f75ec6c60e595ce7a15/src/ott/solvers/linear/implicit_differentiation.py#L199). You mention that GMRES is not stable, so do you think there's an alternative here or that your `NormalCG` offers benefits when compared to running JAX's scipy CG on the symmetrized problem?

**Comment by patrick-kidger** [comment]
One benefit is that `lineax.NormalCG` (unlike `jax.{...}.cg`) performs "stabilisation", where it recomputes the residual every k(=10 by default) steps. This (a) tends to get you more accurate solves, and (b) if you're using float32 then it can also make the difference between success and failure.

Algorithmically speaking, normal CG is probably as good as it gets on your problem -- looking at your code, I understand that you're trying to avoid materialising the matrix, so you have to use an iterative solver. (BiCGStab or GMRES might be better if your problem happens to be suitable for them.)

That said, if a user of OTT happens to have a small problem and is willing to materialise the matrix, then directly calling LU (on the original non-normal equations) will probably be best. Supporting this kind of use case was one of the main motivators for creating Lineax: enabling downstream libraries to use a single interface for all kinds of linear solver, so that a user can write either `SomeDownstreamSolver(linear_solver=lx.LU())` or `SomeDownstreamSolver(linear_solver=lx.NormalCG())` and have everything work with a consistent interface. (Indeed I will be updating Diffrax to depend on Lineax shortly.)

**Comment by marcocuturi** [comment]
Hi @patrick-kidger thanks for the insight. I gave it a try in https://github.com/ott-jax/ott/pull/370

Two comments:
- >=3.9  is a bit of an issue for us, a workaround is to revert to former implementation when 3.8 and to this new implementation when higher
- I had to define this custom linear operator where you can pass the transpose function. For some reason it does not seem to work if I don't do this.

Any insights welcome! Thanks

**Comment by patrick-kidger** [comment]
I'm afraid 3.9 is a hard requirement -- I'm in the process of updating the whole Equinox ecosystem to use that as a minimum version. Indeed the change is due to type hints!

It's a bit mysterious that the custom linear operator is necessary. Do you have a MWE of what goes wrong by default?

Regarding the solver -- note that `lx.AutoLinearSolver(well_posed=False)` will dispatch to either `lx.Diagonal` or `lx.SVD` -- in particular the latter will materialise the matrix. In the symmetric case you probably want `solver=lx.CG` instead.

Regarding the various branches you've got going on -- note that Lineax operators support transposition. I've not tracked every detail, but I can see you've got branching on `n > m`, that you might be able to simplify.

**Comment by marcocuturi** [comment]
> It's a bit mysterious that the custom linear operator is necessary. Do you have a MWE of what goes wrong by default?

can try indeed.

> Regarding the solver -- note that lx.AutoLinearSolver(well_posed=False) will dispatch to either lx.Diagonal or lx.SVD -- in particular the latter will materialise the matrix. In the symmetric case you probably want solver=lx.CG instead.

Makes sense! Will try this then.

> Regarding the various branches you've got going on -- note that Lineax operators support transposition. I've not tracked every detail, but I can see you've got branching on n > m, that you might be able to simplify.

it's not related to transposition, it's related to the matrix inversion lemma, and which block to use to instantiate it. it's arguably not super elegant.

**Pull request closed without merging**
