### PR TITLE
add first version of SCOT demonstration notebook (Gromov-Wasserstein for multi-omics)

### PR DESCRIPTION
**Pull request by antoinebelloir**
### Adds a second biology example to the documentation notebooks. 
The notebook presents an application of OTT's Gromov Wasserstein optimal transport to match single-cell points clouds from two different measurement spaces (e.g. mapping gene expressions measurements to chromatine accessibility measurements). 
It is adapted from *Demetci et al, Gromov-Wasserstein optimal transport to align single-cell multi-omics data, ICML 2020 Workshop on Computational Biology, 2020* (pdf [here](https://icml-compbio.github.io/icml-website-2020/2020/papers/WCBICML2020_paper_51.pdf)).

### CODE REVIEW

**Comment by antoinebelloir** [comment]
<p>Changed to "<strong>Gromov-Wasserstein for multi-omics"</strong></p><p> </p>

---

 <a href='https://app.reviewnb.com/ott-jax/ott/pull/64/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by antoinebelloir** [comment]
<p>Agreed, the introduction paragraphs were too long. I changed it to a way shorter presentation, that sticks better with other notebooks</p><p> </p>

---

 <a href='https://app.reviewnb.com/ott-jax/ott/pull/64/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by antoinebelloir** [comment]
<p>I agree that a comparison of OTT vs POT is useful. I added it to the notebook. You are right to point out the convergence settings : for the contest to be fair, I therefore used POT's default parameters for OTT (maximum number of iterations=1000 and threshold=1e-9) and added a comment to make this explicit. You will see that OTT runs way faster on GPU. I did not run comparison experiences on CPU.</p><p> </p>

---

 <a href='https://app.reviewnb.com/ott-jax/ott/pull/64/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by antoinebelloir** [comment]
<p>Following your comment I used Black to format most of my cells. It's cleaner now</p><p> </p>

---

 <a href='https://app.reviewnb.com/ott-jax/ott/pull/64/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by antoinebelloir** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/ott-jax/ott/pull/64/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by antoinebelloir** [comment]
<p>Agreed, I made a modification within "fin_correspondances" 's body but I could to change "e" to "epsilon" in the arguments without making the code heavier, since "e" is actually a keyword argument used by another method of the SCOT class</p>

---

 <a href='https://app.reviewnb.com/ott-jax/ott/pull/64/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by antoinebelloir** [comment]
<p>See my reply about OTT vs POT comparison. I changed max_iterations to 1000 and I set threshold to 1e-9 to match the POT implementation.</p>

---

 <a href='https://app.reviewnb.com/ott-jax/ott/pull/64/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by antoinebelloir** [comment]
<p>Corrected</p>

---

 <a href='https://app.reviewnb.com/ott-jax/ott/pull/64/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by antoinebelloir** [comment]
<p>Also corrected</p>

---

 <a href='https://app.reviewnb.com/ott-jax/ott/pull/64/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by antoinebelloir** [comment]
<p>I rewrote this cell to make it clearer and to mention the OTT vs POT comparison</p>

---

 <a href='https://app.reviewnb.com/ott-jax/ott/pull/64/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by antoinebelloir** [comment]
<p>I see how using an animation for only two plots looks like an overkill, but I find it useful though to see the crosses (representing chromatin accessibility points mapped to gene expression domain) appear on top of the gene expression domain points (circles). I deleted the precedent visualisation that was a single plot of the two set of points (ie the second frame of the animation) as it was a duplicate</p>

---

 <a href='https://app.reviewnb.com/ott-jax/ott/pull/64/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by antoinebelloir** [comment]
<p>Deleted</p>

---

 <a href='https://app.reviewnb.com/ott-jax/ott/pull/64/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by marcocuturi** [comment]
This is starting to look good! 

May I suggest that you also add the link to that notebook in

https://github.com/ott-jax/ott/blob/main/docs/index.rst

so that it is directly referenced in the doc? 

I would probably add it in the "advanced applications" section

**Comment by marcocuturi** [comment]
Thanks!

**Comment by antoinebelloir** [comment]
It was very interesting to contribute to this notebook  ! Just a detail, the merged notebook has a nice display in the repo pre-visualisation but has two little display issues on the readthedocs.io website :
image
image
I do not know how to fix them

**Comment by marcocuturi** [comment]
Thanks Antoine! I think I fixed that. it seems you cannot put an url on top of a ` ... ` code formatting. You could fix it with a PR, but no worries, I took care of that. Thanks a lot again for this great contribution to the toolbox!!

**Pull request merged**
