### PR TITLE
Pre-commit

### LINKED ISSUE #43: pre-commit
I'd like to suggest using a [pre-commit](https://pre-commit.com/) to mostly unify formatting/add ome simple checks.

For starters, I'd recommend the following:
- [black](https://github.com/psf/black): for formatting (also would switch to 4 spaces instead of 2)
- [isort](https://pycqa.github.io/isort/): to sort imports
- the following hooks from https://github.com/pre-commit/pre-commit-hooks:
  - [check-ast](https://github.com/pre-commit/pre-commit-hooks#check-ast) so that valid Python code is committed
  - [check-merge-conflict](https://github.com/pre-commit/pre-commit-hooks#check-merge-conflict) to not commit files where a merge conflict is present
  - end of line/whitpace handlers: [end-of-file-fixer](https://github.com/pre-commit/pre-commit-hooks#end-of-file-fixer), [trailing-whitespace](https://github.com/pre-commit/pre-commit-hooks#trailing-whitespace) [mixed-line-ending](https://github.com/pre-commit/pre-commit-hooks#mixed-line-ending)

Example file I like using is here, though there are other checks, such as for typing and documentation: https://github.com/theislab/squidpy/blob/master/.pre-commit-config.yaml
`black`/`isort` are configured here: https://github.com/theislab/squidpy/blob/master/pyproject.toml#L5-L58

For new contributors, the workflow would then be:
```bash
git clone https://github.com/ott-jax/ott && cd ott
pip install -e'.[dev]'  # extra `dev` requirements contains `pre-commit` package
pre-commit install
```

### PR DESCRIPTION
**Pull request by michalk8**
This PR introduces some pre-commits, some configuration files, `.gitignore` and a missing RST template for class (related to docs formatting in #66)
Per https://google.github.io/styleguide/pyguide.html#34-indentation and because  `black` doesn't support `2` spaces as indentation, it's now `4` spaces. I've set the max line length to `120` (given current resoution; I always use this), but this can be adapted in `pyproject.toml`.
`flake8` pre-commits are failing, I just wanted to start a discussion whether the style is ok. Afterwards, I will start fixing these.

To try this out, run in the root of the project:
```bash
pre-commit install  # needs to be done only once; will run `pre-commit` before commiting/pushing
pre-commit run --all-files
```

closes #43

### CODE REVIEW

**Comment by marcocuturi** [comment]
thanks so much Michal. I am bit scared by the 4 spaces, because I prefer to keep 80 chars. FWIW, google style also recommends 80 even for 4 spaces :) 

https://google.github.io/styleguide/pyguide.html#32-line-length

the rest is just super nice! thanks so much.

**Comment by marcocuturi** [comment]
any other opinion on this subject (notably the switch from 2 -> 4?) 

for more context::

https://www.reddit.com/r/learnpython/comments/1xfoxz/pep_indentation_using_4_spaces_vs_googles_2_spaces/

I would prefer personally to stick to 2/80 as i find that more efficient

**Comment by marcocuturi** [comment]
This would definitely be my preference, but I am happy to hear about other opinions if there are any out there.

**Comment by LaetitiaPapaxanthos** [comment]
I also would prefer 2 spaces instead of 4, for consistency with the rest of the code and JAX-based packages.

**Comment by marcocuturi** [comment]
I think readibility 80 characters is a big plus. That combined with the multi column views is what convinces me. But I guess this is a question of habit. Overall I think it still makes sense to stick to JAX conventions... maybe next time Michal, when there are less (ex)-googlers around :)

**Comment by michalk8** [comment]
Ok, I've added `yapf` with 80 colwidth and 2 spaces + a linting job, which currently fails because of `flake8`. Will start fixing it in the upcoming days.

**Review by marcocuturi — COMMENTED** [review]
Thanks so much for this macro PR!!

**Pull request merged**
