### PR TITLE
Fix Wrong implementation of u_t(x|z) in Brownian Bridge

### LINKED ISSUE #595: Wrong implementation of u_t(x|z) in Brownian Bridge
Hi,
I was reading the tong et al 23 paper and noticed the implementation might be wrong here. As I was using this flow for my thesis project already.

In the implementation ut() = x1-x0 but in the paper it is
image

https://github.com/ott-jax/ott/blob/828acca41a0c41ce38440ad51896e5c29161cbbd/src/ott/neural/methods/flows/dynamics.py#L143

### PR DESCRIPTION
**Pull request by selmanozleyen**
fixes #595 and changes the naming

### CODE REVIEW

**Comment by marcocuturi** [comment]
Thanks @selmanozleyen ! I think you need to fix the tests as well to comply with your new variable names

**Comment by selmanozleyen** [comment]
Ok, I made the changes, it should be ready review @michalk8  @marcocuturi

**Comment by marcocuturi** [comment]
thanks @selmanozleyen :) the preferred way to ping for review is to use the tool up there, in the right, to assign reviewers :)

**Review by michalk8 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
