### PR TITLE
Added tutorial on Sinkhorn divergence

### PR DESCRIPTION
**Pull request by gjhuizing**
Added a tutorial on Sinkhorn divergence showing Gradient flows of entropic OT and Sinkhorn divergence

### CODE REVIEW

**Comment by gjhuizing** [comment]
Made all requested changes

**Comment by gjhuizing** [comment]
<p>Made it more compact</p>

---

 <a href='https://app.reviewnb.com/ott-jax/ott/pull/282/discussion/#comment-1431213818'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by gjhuizing** [comment]
<p>Good idea, I mentioned it twice here, and also added a link in the intro notebook</p>

---

 <a href='https://app.reviewnb.com/ott-jax/ott/pull/282/discussion/#comment-1431213777'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by gjhuizing** [comment]
<p>thanks, added it!</p>

---

 <a href='https://app.reviewnb.com/ott-jax/ott/pull/282/discussion/#comment-1431212408'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by gjhuizing** [comment]
<p>ok!</p>

---

 <a href='https://app.reviewnb.com/ott-jax/ott/pull/282/discussion/#comment-1431212372'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by gjhuizing** [comment]
Hum, isort seems to fail in the linting, despite running the pre-commit

**Comment by michalk8** [comment]
> Hum, isort seems to fail in the linting, despite running the pre-commit

@gjhuizing can you please try installing `tox` and run `tox -e lint-code`?

Tests are have been fixed in #310, once the linter is fixed and the 2 comments are addressed, will be happy to merge!

**Review by marcocuturi — CHANGES_REQUESTED** [review]
Thanks Geert! a minor change designed to minimize copy pasting and some nuances on why there is a collapse (would also be great to have this pop up without having to tune epsilon)

**Comment by gjhuizing** [comment]
On it! Do you think it would be helpful to show several values of epsilon, or is the default one enough?

**Comment by marcocuturi** [comment]
@gjhuizing I think we can maybe show two animations where, for instance, the default `epsilon` is used, and another bigger epsilon is used, which has an impact on the collapse, and then show that sink div is less sensitive to that setting of `epsilon`.

**Comment by marcocuturi** [comment]
another related point, it might be interesting, since we're doing gradient flow, to set `static_b` to `True` as a parameter when instantiating the `sinkhorn_divergence`

**Comment by gjhuizing** [comment]
@michalk8 fyi, it might be an issue on my end but `nbqa-isort` doesn't sort in the same order locally and in the CI

**Comment by michalk8** [comment]
> @michalk8 fyi, it might be an issue on my end but nbqa-isort doesn't sort in the same order locally and in the CI. Had to modify manually and ignore the pre-commit to pass linting.

We might need to upgrade the `pre-commits` as `pre-commit autoupdate` then.

**Comment by michalk8** [comment]
Re failing tests: they seem to be unrelated (also broken on `main`), need to look and possibly fix (don't like that geom, will most likely deprecate in favor of something else).

**Comment by gjhuizing** [comment]
Hi! just to be sure, is there any action left on my end?

**Comment by michalk8** [comment]
> Hi! just to be sure, is there any action left on my end?

Could you please resolve the conflict? The CI issues has been fixed on `main`. After this, I will give it one last pass, but think we will be able to merge.

**Comment by gjhuizing** [comment]
Okay, done!

**Comment by gjhuizing** [comment]
Thank you! :tada:

**Pull request merged**
